name: dependency_platforms
description: A sample command-line application.
version: 0.0.1
repository: https://github.com/rohitsangwan01/dependency_platforms.git

environment:
  sdk: ^3.5.0

platforms:
  linux:
  macos:
  windows:

dependencies:
  pubspec_parse: ^1.3.0
  http: ^1.2.2
  html: ^0.15.4
  dolumns: ^2.0.1
  console_bars: ^1.2.0
  args: ^2.5.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

executables:
  dependency_platforms: